name: container - samba-domain

on:
  schedule:
    - cron: '11 4 * * 0'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: divialth/samba-dc
  # base path to the dockerfile
  DOCKERFILE_PATH: samba-dc
  # build platform
  BUILD_PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64
  # build variables
  BUILD_DATE: ""
  VERSION: ${{ github.run_id }}-${{ github.run_number }}


jobs:
  build-container:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: set release date
        run: |
          echo "BUILD_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
